name: netpinproc.domain.release
on:
  push:
    branches: [ dev ]  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        VERSION: 1.0.3
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        NUGETAPIKEY: --api-key ${{ secrets.GITHUB_TOKEN }} --source github
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x
      - name: Add Nuget FlippingFlips Source
        run: dotnet nuget add source --username USERNAME --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FlippingFlips/index.json"      
      # dotnet nuget pack projects
      - name: Dotnet Pack - Nuget
        run: |
            dotnet pack src -c Release
      # dotnet nuget push packages
      - name: Nuget Symbols
        run: dotnet nuget push "src/.nuget/NetPinProc.Domain.${VERSION}.snupkg" ${NUGETAPIKEY}
      - name: Nuget Domain
        run: dotnet nuget push "src/.nuget/NetPinProc.Domain.${VERSION}.nupkg" ${NUGETAPIKEY}